# syntax=docker/dockerfile:1
FROM golang:1.24 AS builder

WORKDIR /app
COPY go.mod main.go ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /goapp

FROM gcr.io/distroless/static-debian11
COPY --from=builder /goapp /goapp
USER nonroot:nonroot
CMD ["/goapp"]
